#ifndef CORE_VERSION_H
#define CORE_VERSION_H

#define OS_NAME "Sage Aasvogel"
#define MAJOR_VERSION 0
#define MINOR_VERSION 1
#define REVISION_NUMBER 0

#ifndef VERSION_SUFFIX
#define VERSION_SUFFIX
#endif

#define FULL_VERSION_IDENTIFIER "v" STRINGIFY(MAJOR_VERSION) "." STRINGIFY(MINOR_VERSION) "." STRINGIFY(REVISION_NUMBER) VERSION_SUFFIX

#define _STRINGIFY(s) #s
#define STRINGIFY(s) _STRINGIFY(s)

#endif
