SET(CMAKE_SYSTEM_NAME Generic)

IF(${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} VERSION_LESS 3.6)
    INCLUDE(CMakeForceCompiler)
    CMAKE_FORCE_C_COMPILER(i686-elf-gcc GNU)
ELSE()
    SET(CMAKE_C_COMPILER i686-elf-gcc)
    SET(CMAKE_TRY_COMPILE_TARGET STATIC_LIBRARY)
ENDIF()


SET(CMAKE_ASM_COMPILER i686-elf-gcc)

SET(CMAKE_C_LINK_EXECUTABLE "i686-elf-ld <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> -o <TARGET>")

SET(QEMU_COMMAND "qemu-system-i386")
