INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYTSTEM_NAME Generic)

CMAKE_FORCE_C_COMPILER(i686-elf-gcc GNU)
SET(CMAKE_ASM_COMPILER i686-elf-gcc)

SET(CMAKE_C_LINK_EXECUTABLE "i686-elf-ld <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> -o <TARGET>")

SET(QEMU_COMMAND "qemu-system-i386")
